//#pragma once
//
//struct MIDI
//{
//    unsigned number;
//    const char* name;
//    int n;
//};
//
//const static MIDI midi[] =
//        {
//                {.number=12,    .name="C0",     .n=-8},
//                {.number=13,    .name="Db0",    .n=-7},
//                {.number=14,    .name="D0",     .n=18.35405},
//                {.number=15,    .name="Eb0",    .n=19.44544},
//                {.number=16,    .name="E0",     .frequency=20.60172},
//                {.number=17,    .name="F0",     .frequency=21.82676},
//                {.number=18,    .name="Gb0",    .frequency=23.12465},
//                {.number=19,    .name="G0",     .frequency=24.49971},
//                {.number=20,    .name="Ab0",    .frequency=25.95654},
//                {.number=21,    .name="A0",     .frequency=27.50000},
//                {.number=22,    .name="Bb0",    .frequency=29.13524},
//                {.number=23,    .name="B0",     .frequency=30.86771},
//                {.number=24,    .name="C1",     .frequency=32.70320},
//                {.number=25,    .name="Db1",    .frequency=34.64783},
//                {.number=26,    .name="D1",     .frequency=36.70810},
//                {.number=27,    .name="Eb1",    .frequency=38.89087},
//                {.number=28,    .name="E1",     .frequency=41.20344},
//                {.number=29},
//                {.number=30},
//                {.number=31},
//                {.number=32},
//                {.number=33},
//                {.number=34},
//                {.number=35},
//                {.number=36},
//                {.number=37},
//                {.number=38},
//                {.number=39},
//                {.number=40},
//                {.number=41},
//                {.number=42},
//                {.number=43},
//                {.number=44},
//                {.number=45},
//                {.number=46},
//                {.number=47},
//                {.number=48},
//                {.number=49},
//                {.number=50},
//                {.number=51},
//                {.number=52},
//                {.number=53},
//                {.number=54},
//                {.number=55},
//                {.number=56},
//                {.number=57},
//                {.number=58},
//                {.number=59},
//                {.number=60},
//                {.number=61},
//                {.number=62},
//                {.number=63},
//                {.number=64},
//                {.number=65},
//                {.number=66},
//                {.number=67},
//                {.number=68},
//                {.number=69},
//                {.number=70},
//                {.number=71},
//                {.number=72},
//                {.number=73},
//                {.number=74},
//                {.number=75},
//                {.number=76},
//                {.number=77},
//                {.number=78},
//                {.number=79},
//                {.number=80},
//                {.number=81},
//                {.number=82},
//                {.number=83},
//                {.number=84},
//                {.number=85},
//                {.number=86},
//                {.number=87},
//                {.number=88},
//                {.number=89},
//                {.number=90},
//                {.number=91},
//                {.number=92},
//                {.number=93},
//                {.number=94},
//                {.number=95},
//                {.number=96},
//                {.number=97},
//                {.number=98},
//                {.number=99},
//                {.number=100},
//                {.number=101},
//                {.number=102},
//                {.number=103},
//                {.number=104},
//                {.number=105},
//                {.number=106},
//                {.number=107},
//                {.number=108},
//                {.number=109},
//                {.number=110},
//                {.number=111},
//                {.number=112},
//                {.number=113},
//                {.number=114},
//                {.number=115},
//                {.number=116},
//                {.number=117},
//                {.number=118},
//                {.number=119}
//        };